paths:
  data_parent_dir: data
  models_parent_dir: models
  reports_parent_dir: reports
  figures_parent_dir: figures
  data:
    raw_data: ${paths.data_parent_dir}/raw
    interim_data: ${paths.data_parent_dir}/interim
    processed_data: ${paths.data_parent_dir}/processed
    external_data: ${paths.data_parent_dir}/external

dataset:
  target_col: "Survived"
  id_col: "PassengerId"
  test_size: 0.2
  random_state: 42

names:
  train_data: "train"
  test_data: "test"
  val_data: "val"
  model_name: "random_forest"
  submission_name: "submission"
  target_name: "target"

hyperparameters:
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42

tuning:
  n_iter: 10
  cv: 5
  random_forest:
    n_estimators:
      - 50
      - 100
      - 200
    max_depth:
      - 5
      - 10
      - 15
    min_samples_split:
      - 2
      - 5
    min_samples_leaf:
      - 1
      - 2
    max_features:
      - "sqrt"
      - "log2"

pipeline_config:
  drop:
    - PassengerId
    - Name
    - Ticket
    - Cabin
  imputation:
    mean:
      - Age
  scaling:
    standard:
      - Age
      - Fare
    minmax:
      - FamilySize
      - TicketGroupSize
  encoding:
    onehot:
      - Sex
    ordinal:
      - Embarked
      - Deck
      - Title
mlflow:
  experiment_name: "titanic_experiment"
  tracking_uri: "http://localhost:8080"
  is_tracking_enabled: false