channels:
- conda-forge
dependencies:
- python=3.11.6
- pip<=25.1.1
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - loguru==0.7.3
  - numpy==2.2.6
  - pandas==2.2.3
  - python-dotenv==1.1.0
  - scikit-learn==1.6.1
  - scipy==1.15.3
  - tqdm==4.67.1
name: mlflow-env
